"""Mandatory Voicing

Revision ID: 32205284556f
Revises: b08bb8ec24b8
Create Date: 2026-06-15 00:39:24.242980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "32205284556f"
down_revision: Union[str, Sequence[str], None] = "b08bb8ec24b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song") as batch_op:
        batch_op.alter_column("voicing", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song") as batch_op:
        batch_op.alter_column("voicing", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
