"""User

Revision ID: 37a36bf51979
Revises: c175736d5f44
Create Date: 2026-06-13 15:34:10.665034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "37a36bf51979"
down_revision: Union[str, Sequence[str], None] = "c175736d5f44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("password_encoded", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="user_primary_id"),
    )
    op.create_table(
        "user_song_xref",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["song.id"], name="foreign_song_id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="foreign_user_id"),
        sa.PrimaryKeyConstraint("user_id", "song_id", name="user_song_primary_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_song_xref")
    op.drop_table("user")
    # ### end Alembic commands ###
