"""User Token

Revision ID: 4bca77acae83
Revises: 37a36bf51979
Create Date: 2026-06-13 16:42:53.880272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4bca77acae83"
down_revision: Union[str, Sequence[str], None] = "37a36bf51979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(sa.Column("auth_token", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("auth_token_exp", sa.TIMESTAMP(timezone=True), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column("auth_token_exp")
        batch_op.drop_column("auth_token")
    # ### end Alembic commands ###
