"""Title Sort

Revision ID: 587b8dde6db8
Revises: 32205284556f
Create Date: 2026-06-15 12:46:31.106236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587b8dde6db8'
down_revision: Union[str, Sequence[str], None] = '32205284556f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song') as batch_op:
        batch_op.add_column( sa.Column('song_name_sort', sa.String(), nullable=True))

    op.execute("UPDATE song SET song_name_sort=song_name")

    with op.batch_alter_table("song") as batch_op:
        batch_op.alter_column("song_name_sort", existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'song_name_sort')
    # ### end Alembic commands ###
