"""Voice Part

Revision ID: 6ee556a567ad
Revises: 4bca77acae83
Create Date: 2026-06-13 18:05:49.487133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6ee556a567ad"
down_revision: Union[str, Sequence[str], None] = "4bca77acae83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    voicepart = sa.Enum("TENOR", "LEAD", "BARI", "BASS", name="voicepart")
    voicepart.create(op.get_bind())
    with op.batch_alter_table("user_song_xref") as batch_op:
        batch_op.add_column(sa.Column("voice_part", voicepart, nullable=False))
        batch_op.drop_constraint("user_song_primary_id")
        batch_op.create_primary_key(
            "user_song_primary_id", columns=["user_id", "song_id", "voice_part"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_song_xref") as batch_op:
        batch_op.drop_constraint("user_song_primary_id")
        batch_op.create_primary_key(
            "user_song_primary_id", columns=["user_id", "song_id"]
        )
        batch_op.drop_column("user_song_xref", "voice_part")
    # ### end Alembic commands ###
