"""Contributor Primary

Revision ID: b08bb8ec24b8
Revises: 6ee556a567ad
Create Date: 2026-06-14 21:56:56.618824

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b08bb8ec24b8"
down_revision: Union[str, Sequence[str], None] = "6ee556a567ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contributor_xref") as batch_op:
        batch_op.drop_constraint("contributor_song_primary_id")
        batch_op.create_primary_key(
            "contributor_song_primary_id",
            columns=["song_id", "contributor_id", "contribution_type"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contributor_xref") as batch_op:
        batch_op.drop_constraint("contributor_song_primary_id")
        batch_op.create_primary_key(
            "contributor_song_primary_id", columns=["song_id", "contributor_id"]
        )
    # ### end Alembic commands ###
