"""Song

Revision ID: ba084e60b817
Revises:
Create Date: 2026-06-13 14:18:49.267739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ba084e60b817"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("song_name", sa.String(), nullable=False),
        sa.Column("voicing", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="song_primary_id"),
        sa.UniqueConstraint("stock_id", name="unique_stock_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song")
    # ### end Alembic commands ###
