"""Contributors

Revision ID: c175736d5f44
Revises: ba084e60b817
Create Date: 2026-06-13 14:36:39.876132

"""

from typing import Sequence, Union

from alembic import op
from asyncpg import DuplicateObjectError
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError

# revision identifiers, used by Alembic.
revision: str = "c175736d5f44"
down_revision: Union[str, Sequence[str], None] = "ba084e60b817"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    contribution_type_enum = sa.Enum(
        "COMPOSER", "LYRICIST", "ARRANGER", name="contributiontype"
    )
    try:
        contribution_type_enum.create(op.get_bind())
    except (DuplicateObjectError, ProgrammingError):
        pass

    op.create_table(
        "contributor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("person_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="contributor_primary_id"),
    )
    op.create_table(
        "contributor_xref",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("contributor_id", sa.Integer(), nullable=False),
        sa.Column("contribution_type", contribution_type_enum, nullable=False),
        sa.ForeignKeyConstraint(
            ["contributor_id"], ["contributor.id"], name="foreign_contributor_id"
        ),
        sa.ForeignKeyConstraint(["song_id"], ["song.id"], name="foreign_song_id"),
        sa.PrimaryKeyConstraint(
            "song_id", "contributor_id", name="contributor_song_primary_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contributor_xref")
    op.drop_table("contributor")
    # ### end Alembic commands ###
