"""Unique User-Song-Part

Revision ID: c747c8e05d36
Revises: 587b8dde6db8
Create Date: 2026-07-30 22:00:03.684272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c747c8e05d36"
down_revision: Union[str, Sequence[str], None] = "587b8dde6db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_song_xref") as batch_op:
        batch_op.create_unique_constraint(
            "unique_user_song_part", ["user_id", "song_id", "voice_part"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_song_xref") as batch_op:
        batch_op.drop_constraint("unique_user_song_part", type_="unique")
    # ### end Alembic commands ###
